name: AppLauncher
targets:
  AppLauncher:
    type: application
    platform: macOS
    deploymentTarget: "12.0"
    sources: 
      - Sources/AppLauncher
    settings:
      INFOPLIST_FILE: Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: local.AppLauncher
      ENABLE_PREVIEWS: YES
